---
kind: pipeline
name: build

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: ghcr.io
      username: 
        from_secret: github_username
      password: 
        from_secret: github_token
      repo: ghcr.io/simoneromano96/thunder/api
      context: .
      dockerfile: ./.docker/app.dockerfile
      auto_tag: true
      target: production
      config:
        from_secret: docker_auth_config

# trigger:
#   event:
#     exclude:
#       - promote
#       - rollback

---
kind: pipeline
type: ssh
name: deploy-beta

server:
  host:
    from_secret: host
  user:
    from_secret: user
  # port:
  #   from_secret: port
  ssh_key:
    from_secret: ssh_key

steps:
  - name: deploy-beta-api
    environment:
      GITHUB_USERNAME:
        from_secret: github_username
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - docker login https://ghcr.io --username $GITHUB_USERNAME --password $GITHUB_TOKEN
      - cd /home/simone/docker/thunder/beta
      - docker-compose pull && docker-compose up --detach --build api

depends_on:
  - build

trigger:
  event:
    exclude:
      - promote
      - rollback

---
kind: pipeline
type: ssh
name: deploy-production

server:
  host:
    from_secret: host
  user:
    from_secret: user
  # port:
  #   from_secret: port
  ssh_key:
    from_secret: ssh_key

steps:
  - name: deploy-production-api
    environment:
      GITHUB_USERNAME:
        from_secret: github_username
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - docker login https://ghcr.io --username $GITHUB_USERNAME --password $GITHUB_TOKEN
      - cd /home/simone/docker/thunder/prod
      - docker-compose pull && docker-compose up --detach --build api

depends_on:
  - build

trigger:
  event:
    - promote
    - rollback
  target:
    - production

---
kind: pipeline
type: ssh
name: deploy-production-together

server:
  host:
    from_secret: host
  user:
    from_secret: user
  # port:
  #   from_secret: port
  ssh_key:
    from_secret: ssh_key

steps:
  - name: deploy-production-together-api
    environment:
      GITHUB_USERNAME:
        from_secret: github_username
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - docker login https://ghcr.io --username $GITHUB_USERNAME --password $GITHUB_TOKEN
      - cd /home/simone/docker/thunder/together-firenze
      - docker-compose pull && docker-compose up --detach --build api

depends_on:
  - build

trigger:
  event:
    - promote
    - rollback
  target:
    - production-together
